name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:
    inputs:
      response_label:
        description: 'Label to track issues/PRs needing response'
        required: true
        default: 'needs:response'
        type: string

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: -1
          days-before-issue-close: 30
          stale-issue-label: ${{ inputs.response_label }}
          close-issue-message: "This issue was closed because it has been inactive for 30 days since being marked as `${{ inputs.response_label }}`."

          days-before-pr-stale: -1
          days-before-pr-close: 30
          stale-pr-label: ${{ inputs.response_label }}
          close-pr-message: "This PR was closed because it has been inactive for 30 days since being marked as '${{ inputs.response_label }}'."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
